### ISSUE TITLE
why does it flicker?

### ISSUE THREAD

**Issue by voltuer** [gineer01/matrix-rain#1] opened 2020-05-20 06:39 UTC
Hi, I really loved your animation, it' awesomely similar to the movie's one in terms of lines slowly fading and colors; however, the flicker is really annoying, so I'm wondering why it can't work like [matrix-rain](https://github.com/nojvek/matrix-rain) which is written in NodeJS and doesn't flicker at all.

I don't know too much python to attempt to fix it myself.

**Comment by gineer01** [comment] 2020-05-20 08:11
I notice the flickering too if the screen is too big, so the workaround is to reduce the terminal window size to smaller. I'm guessing a bigger window has more characters and requires more work to update the animation (each character on the screen needs to be updated to simulate the Matrix effect), and it flickers. Cheers!

**Comment by gineer01** [comment] 2020-05-20 08:22
Actually, I find increasing the font size for terminal works better than reducing the terminal window size. It has the same performance impact, but I can see the characters better. I increase the font size to 40. 😀

**Comment by voltuer** [comment] 2020-05-20 17:49
Thanks for replying. I'm trying to reach a cleaner solution by commenting the `clear` line and putting an empty character at the end of the tail, and i'm kind of succeeding except for the speed variation: I'm not being able to find the tail is when speed > 1

So here I set speed to always be 1, enabled gradient, disabled clearing. Works perfectly except for speed variation :D 

![mt](https://user-images.githubusercontent.com/197329/82481562-7ca8b780-9aa3-11ea-9d9b-a68aa62ad7de.gif)


```python
#!/usr/bin/env python3

import random
import curses
import time
import sys

#Sleep between frame after refresh so that user can see the frame. Value 0.01 or lower results in flickering because the
# animation is too fast.
SLEEP_BETWEEN_FRAME = .04

#How fast the rain should fall. In config, we change it according to screen.
FALLING_SPEED = 2

#The max number of falling rains. In config, we change it according to screen.
MAX_RAIN_COUNT = 10

#Color gradient for rain
COLOR_STEP = 20
START_COLOR_NUM = 128 #The starting number for color in gradient to avoid changing the first 16 basic colors
NUMBER_OF_COLOR = 40
USE_GRADIENT = True


#Reset the config value according to screen size
def config(stdscr):
    curses.curs_set(0)
    stdscr.nodelay(True)

    init_colors()

    global MAX_RAIN_COUNT
    MAX_RAIN_COUNT = curses.COLS//3

    global FALLING_SPEED
    FALLING_SPEED = 1 + curses.LINES//25


def init_colors():
    curses.start_color()
    global USE_GRADIENT
    USE_GRADIENT = curses.can_change_color()  # use xterm-256 if this is false

    if USE_GRADIENT:
        curses.init_color(curses.COLOR_WHITE, 1000, 1000, 1000)
        for i in range(NUMBER_OF_COLOR + 1):
            green_value = (1000 - COLOR_STEP * NUMBER_OF_COLOR) + COLOR_STEP * i
            curses.init_color(START_COLOR_NUM + i, 0, green_value, 0)
            curses.init_pair(START_COLOR_NUM + i, START_COLOR_NUM + i, curses.COLOR_BLACK)
    else:
        curses.init_pair(1, curses.COLOR_GREEN, curses.COLOR_BLACK)


def get_matrix_code_chars():
    l = [chr(i) for i in range(0x21, 0x7E)]
    # half-width katakana. See https://en.wikipedia.org/wiki/Halfwidth_and_fullwidth_forms
    l.extend([chr(i) for i in range(0xFF66, 0xFF9D)])
    return l

MATRIX_CODE_CHARS = get_matrix_code_chars()

def random_char():
    return random.choice(MATRIX_CODE_CHARS)

def random_rain_length():
    # return 5
    return random.randint(curses.LINES//2, curses.LINES)

def rain(stdscr, pool):
    while True:
        x = random.choice(pool)
        pool.remove(x)
        max_length = random_rain_length()
        speed = random.randint(1, FALLING_SPEED)
        yield from animate_rain(stdscr, x, max_length, speed)
        pool.append(x)

def animate_rain(stdscr, x, max_length, speed=FALLING_SPEED):
    head, middle, tail = 0,0,0

    speed = 1

    while tail < curses.LINES:
        middle = head - max_length//2
        if (middle < 0):
            middle = 0

        tail = head - max_length
        if (tail < 0):
            tail = 0

        show_body(stdscr, head, middle, tail, x, speed)

        show_head(stdscr, head, x)

        head = head + speed
        yield


def show_head(stdscr, head, x):
    if head < curses.LINES:
        stdscr.addstr(head, x, random_char(), curses.color_pair(0) | curses.A_STANDOUT)


def show_body(stdscr, head, middle, tail, x, speed):
    if USE_GRADIENT:
        for i in range(tail, min(head, curses.LINES)):
            stdscr.addstr(i, x, random_char(), get_color(i, head, tail))
            if i >= head-tail-1 and (head-tail-speed>0): 
                stdscr.addstr(tail-1, x, " ", get_color(i, head, tail))

    else:
        for i in range(tail, min(middle, curses.LINES)):
            stdscr.addstr(i, x, random_char(), curses.color_pair(1))
        for i in range(middle, min(head, curses.LINES)):
            stdscr.addstr(i, x, random_char(), curses.color_pair(1) | curses.A_BOLD)


def get_color(i, head, tail):
    color_num = NUMBER_OF_COLOR - (head - i) + 1
    if color_num < 0:
        color_num = 0
    return curses.color_pair(START_COLOR_NUM + color_num)


def main(stdscr):
    #stdscr.addstr(0, 0, "Press any key to start. Press any key (except SPACE) to stop.")
    #ch = stdscr.getch() #Wait for user to press something before starting
    config(stdscr)

    rains = []
    pool = list(range(curses.COLS - 1))

    while True:
        add_rain(rains, stdscr, pool)

        #stdscr.clear()
        for r in rains:
            next(r)

        ch = stdscr.getch()
        if ch != curses.ERR and ch != ord(' '): #Use space to proceed animation if nodelay is False
            break

        time.sleep(SLEEP_BETWEEN_FRAME)

def add_rain(rains, stdscr, pool):
    if (len(rains) < MAX_RAIN_COUNT) and (len(pool) > 0):
        rains.append(rain(stdscr, pool))

if __name__ == "__main__":
    curses.wrapper(main)

```

**Comment by gineer01** [comment] 2020-05-20 19:08
Interesting. "clear()" might be the cause of the flicker; it's probably unnecessary because we just overwrite the existing characters with new characters. Why is "putting an empty character at the end of the tail" needed?

**Comment by gineer01** [comment] 2020-05-20 20:19
I've got the "an empty character at the end of the tail" now. I've just pushed a fix for the flickering issue using your suggestion. Thanks for looking into it!

**Comment by voltuer** [comment] 2020-05-20 20:39
great! I see you added some documentation as well. I would really get rid of the "press any key", i think one wants to just see it working instead of having to press one more key. Also a mention for my hard work finding the fix wouldn't hurt. Great work!

**Comment by gineer01** [comment] 2020-05-20 22:30
Sure, I'll add you to README.md to properly attribute your contribution. Would you like your name mentioned as "sebolio" or a different name?

**Comment by voltuer** [comment] 2020-05-20 23:39
That would do, yes

**Comment by voltuer** [comment] 2020-05-21 02:51
Another contribution:

Since in the movie the "head" is a white character with no background, I changed the color of the function to get a bold white color which looks more genuine:

```
def show_head(stdscr, head, x):
    if head < curses.LINES:
        stdscr.addstr(head, x, random_char(), curses.COLOR_WHITE | curses.A_BOLD)
```

Movie:
![Digital_rain_animation_medium_letters_shine](https://user-images.githubusercontent.com/197329/82518034-6a9f3700-9aec-11ea-9ef9-eef37c923504.gif)

New function:
![image](https://user-images.githubusercontent.com/197329/82517901-290e8c00-9aec-11ea-9728-410011a9ece1.png)

**Comment by gineer01** [comment] 2020-05-21 06:18
I did try it in test_curses.py in this repo and didn't like it, so I went with A_STANDOUT, the best highlighting mode according to this doc 😀 (https://docs.python.org/3/howto/curses.html).

A_BOLD | Extra bright or bold text
A_STANDOUT | The best highlighting mode available

I suppose A_BOLD is more like the movie, but it is subjective preference (I didn't like it because I felt head was not much different from body). You can fork this repo and customize (use test_curses.py to help with your experiment). For example, use a brighter green color to look more like the movie?

**Comment by voltuer** [comment] 2020-05-22 00:01
I agree that, when looked from afar, it does actually look very good; but when looked closely (especially with large font sizes, as the script documentation suggests), they look just like white squares, making it feel more like worms than actual rain. I just wish there was something in the middle, like a super-bold escape code.

**Comment by gineer01** [comment] 2020-05-22 21:14
You're right. A_STANDOUT does look bad in bigger font. I guess that's why they went with A_BOLD style for the movie because they zoom into the characters in the movie. 😀 I've pushed a commit to add option to switch between the two styles (press 'h' to change style). Cheers!

**Closed as completed** 2020-09-17 23:48 UTC
